author = 'Oxalin'
country_code = 'GB'
description = 'The West Anglia Main Line between Harlow Town and Cambridge North, and the Stansted Airport branch'
display_name = 'West Anglia Main Line'
doc_files = [ 'West Anglia Main Line.md' ]
factual = true
img_files = [ 'West_Anglia_Main_Line.bmp' ]
name = 'West Anglia Main Line'
release_date = '2022-03-24'
year = 2022
signal_position = "left"
rly_file = 'West Anglia Main Line.rly'
ttb_files = [ 'West Anglia Main Line 23-03-22.ttb' ]
version = '1.0.0'
